version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"

  api-tests:
    profiles: ["test"]
    build:
      context: .
      dockerfile: api/Dockerfile.test
