"""Centralized constants for quick-win technical debt cleanup."""

REDIS_REST_CALL_TIMEOUT_SECONDS = 0.8
UPSTASH_HTTP_TIMEOUT_SECONDS = 1.5
UPSTASH_HTTP_CONNECT_TIMEOUT_SECONDS = 0.75

MESSAGE_GATE_DEFAULT_TIMEOUT_SECONDS = 0.8
STREAM_IDEMPOTENCY_TTL_MIN_SECONDS = 60
STREAM_IDEMPOTENCY_TTL_MAX_SECONDS = 120
STREAM_IDEMPOTENCY_STALE_MIN_SECONDS = 5

RATE_LIMIT_HOURLY_WINDOW_MINUTES = 60
RATE_LIMIT_HOURLY_WINDOW_SECONDS = RATE_LIMIT_HOURLY_WINDOW_MINUTES * 60

PROVIDER_USAGE_TTL_SECONDS = 86400
